external-dns:

  serviceAccount:
    create: true
    labels:
      azure.workload.identity/use: "true"
    annotations:
      azure.workload.identity/client-id: e3dbe873-2f72-4fd3-aad7-c584d1ca94d6

  extraVolumes:
    - name: azure-config-file
      secret:
        secretName: external-dns-azure

  extraVolumeMounts:
    - name: azure-config-file
      mountPath: /etc/kubernetes
      readOnly: true
    
  podLabels:
    azure.workload.identity/use: "true"

  sources:
    - ingress

  provider:
    name: azure # or azure-private-dns

  logLevel: debug